>>> f = open('chai.py')
raw method of using the __next__ response
>>> f.__next__()
exceptions are not handled well here
‘import time\n'

>>> f.__next__()

"print ("

>>> fu

‘username = "hitesh"\n'

>>> f.__next__()

‘print (username) '

>>> f.__next__()

Traceback (most recent call last):
File "<stdin>", Line 1, in <module>

StopIteration

>> fl
